### PR TITLE
Set unique research hub category

### PR DESCRIPTION
**Pull request by csebianlander**
Recently, a new "Research Hub" filterable page was created that was intended to filter based on specific unique categories. Based on feedback from the requesting stakeholder and some internal testing, it seems this filter does not currently work properly because the two new Research categories ("Industry and markets" and "Data point") have identical IDs to those equivalents under the standard Report categories. Attempting to modify the ID within Wagtail fails, presumably because Wagtail sees either one as equivalent

Regardless, this PR addresses the stakeholder desire for this page to house specific and unique pages within the Research & Reports section by creating a unique category for such pages: "Office of Research Report". This will need to be applied to pages manually after being created and updated, but the stakeholder has already provided the pages where this needs to be done, so it should be straightforward.

This will remain a draft PR until the stakeholder confirms that the name chosen for the new category is approved on their end.

---

## Additions

- New category under "Research Hub" page type: `Office of Research Report`

## Removals

- Existing categories under "Research Hub" page type: `Industry and markets`, `Data point`

## How to test this PR

1. localhost
2. Modify an existing document detail page under Research & Reports to the category "Office of Research Report", then publish
3. Confirm that said page now appears on both the Research & Reports (/research-reports/) _and_ Research Hub (/data-research/research-hub/) pages

## Checklist

- [ ] PR has an informative and human-readable title
  - PR titles are used to generate the change log in [releases](../../releases); good ones make that easier to scan.
  - Consider prefixing, e.g., "Mega Menu: fix layout bug", or "Docs: Update Docker installation instructions".
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)
- [ ] Future todos are captured in comments and/or tickets
- [ ] Project documentation has been updated, potentially one or more of:
  - [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in the `/docs` folder) – for basic, close-to-the-code docs on working with this repo
  - CFGOV/platform wiki on GHE – for internal CFPB developer guidance
  - CFPB/hubcap wiki on GHE – for internal CFPB design and content guidance

### CODE REVIEW

**Comment by chosak** [comment]
> This will need to be applied to pages manually after being created and updated, but the stakeholder has already provided the pages where this needs to be done, so it should be straightforward.

How many pages are we talking about? You could also create a data migration to automatically change categories on pages; see #7288 for an example.

**Comment by csebianlander** [comment]
> How many pages are we talking about? You could also create a data migration to automatically change categories on pages; see #7288 for an example.

Less than 100, more than 50. I'll look into that example and figure out which way would ultimately be faster/easier. Thanks!

**Comment by csebianlander** [comment]
@chosak @wpears this is ready for final review and merging, along with #7371

**Review by chosak — APPROVED** [review]
For future searchability: final new category name is "Office of Research Publication".

**Pull request merged**
