### PR TITLE
Create dedicated SecondaryNav component

### PR DESCRIPTION
**Pull request by anselmbradford**
Disentangle expandables from our standard secondary nav and create a dedicated component. 

## Additions

- Create dedicated SecondaryNav component.

## Changes

- Shorten secondary-navigation name to secondary-nav.
- Merge `nav-link` component macro into secondary nav templates.
- Remove top border from secondary nav

## How to test this PR

1. Secondary navs on the following should still function the same as prod:

- http://localhost:8000/data-research/small-business-lending/filing-instructions-guide/2024-guide/
- http://localhost:8000/rules-policy/regulations/1002/
- http://localhost:8000/paying-for-college/your-financial-path-to-graduation/
- http://localhost:8000/enforcement/payments-harmed-consumers/

### CODE REVIEW

**Comment by mistergone** [comment]
👍  This does not appear to break any of Paying for College's Financial Path to Graduation tool!

**Review by brandon-rusk — APPROVED** [review]
Nice work! 🎉

**Comment by contolini** [comment]
@anselmbradford I brought over the failing regression tests from https://github.com/cfpb/consumerfinance.gov/pull/7738. I'll see if I can get them green.

**Comment by anselmbradford** [comment]
🫗 for @brandon-rusk's last PR approval

**Pull request merged**
