### PR TITLE
Update to DS@3.4.8 and update buttons and pagination, etc

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- Update buttons and pagination to use new flex-based layouts and remove button icon-related class names.
- Use `u-small-text--subtle` from the DS.
- Migrate `attach` to `behaviorAttach`.

## How to test this PR

1. Check [prepaid products agreements db](http://localhost:8000/data-research/prepaid-accounts/search-agreements/) and check that the pagination looks fine.
1. Check [the disclosures tool](http://localhost:8000/paying-for-college2/understanding-your-financial-aid-offer/offer/?iped=154022&pid=BAHCA&totl=70950&tuit=14160&hous=7109&book=1150&tran=500&othr=4743&pelg=0&schg=&stag=&othg=&mta=&gib=&wkst=0&ppl=&parl=&perl=&subl=3500&unsl=6000&gpl=&prvl=&prvi=&prvf=&insl=&insi=&inst=&oid=4D0B9265B45716DF4B81EEB4BE117E1DF69871AF) and see that the button group for navigating steps has the buttons properly spaced apart and that the step 2 loading icon is on the right.
2. Check the [gradpath tool](http://localhost:8000/paying-for-college/your-financial-path-to-graduation/) and see that the navigation buttons have centered text and are unchanged to prod.
3. Check the [Before You Claim tool](http://localhost:8000/consumer-tools/retirement/before-you-claim/) and enter dob and income amounts and see that the loading icon on the submit button works.
4. Check http://localhost:8000/privacy/disclosure-consent/ and http://localhost:8000/privacy/records-access/ form and edit the submit button (or submit test data) to see that loading icon appears when the `a-btn--hide-icon` class is removed.
5. Check video close button after playing a video, such as http://localhost:8000/about-us/blog/addressing-racial-inequities-consumer-finance-markets/
6. Check </> buttons on http://localhost:8000/owning-a-home/loan-estimate/

## Screenshots

Before:

Screenshot 2024-11-12 at 8 37 25 AM

Screenshot 2024-11-12 at 8 43 33 AM

Screenshot 2024-11-12 at 8 50 16 AM

After:

Screenshot 2024-11-12 at 8 36 47 AM

Screenshot 2024-11-12 at 8 43 39 AM

Screenshot 2024-11-12 at 8 48 41 AM

### CODE REVIEW

**Comment by paulhyland** [comment]
@anselmbradford - checked all the file updates and none of them affect our GTM triggers. For buttons, we only look for the classes a-btn and btn (the latter used by Mosaic). 

So I approve from my end, but since I don't know if one of the other reviewers needs to run the tests under "How to test this PR", I'm not approving/triggering the merge.

**Comment by anselmbradford** [comment]
Reviewers, the SonarCloud failure is for the heavy amount of duplication between https://www.consumerfinance.gov/privacy/disclosure-consent/ and https://www.consumerfinance.gov/privacy/records-access/, which predates this PR.

**Comment by wpears** [comment]
The video button looks weird to me, see:
Screenshot 2024-11-13 at 10 36 32 AM

Seems like the icon should be to the right of the vertical line or the vertical line should not exist.

**Comment by anselmbradford** [comment]
> The video button looks weird to me, see:

Fixed!

**Comment by anselmbradford** [comment]
FYI I force pushed

**Review by wpears — APPROVED** [review]
🆒

**Pull request merged**
