### PR TITLE
Fix Docker build failures

### PR DESCRIPTION
**Pull request by chosak**
Trying to build the Docker image for this project following the [instructions](https://cfpb.github.io/consumerfinance.gov/running-docker/#just-docker) using this command:

```sh
docker build . -t your-desired-image-name
```

has two issues:

1. First, the frontend build fails due to "Cannot find package 'sass'". This is because the use of "production" for `FRONTEND_TARGET` [in frontend.sh](https://github.com/cfpb/consumerfinance.gov/blob/b63f58fd824eca2a17c099f9fd2606f1b38670b7/frontend.sh#L50-L53) does a `yarn install --production` which excludes devDependencies, which is what [pulls in sass](https://github.com/cfpb/consumerfinance.gov/blob/b63f58fd824eca2a17c099f9fd2606f1b38670b7/package.json#L39-L40). ~~To fix this, I've modified the Dockerfile to remove use of `FRONTEND_TARGET` and frontend.sh, and just call `yarn` and `yarn run build` directly instead.~~ See below for fix.
2. We require that the Django `SECRET_KEY` setting be set [in our production settings](https://github.com/cfpb/consumerfinance.gov/blob/b63f58fd824eca2a17c099f9fd2606f1b38670b7/cfgov/cfgov/settings/production.py#L121) (which is what is used in the Dockerfile). The Dockerfile executes `manage.py collectstatic` in order to collect static files, but this fails if the secret key hasn't been provided. But we shouldn't need to provide a secret key value just to _build_ our Docker image -- it should be something we provide at runtime. To get around this I've added a dummy secret key just for the `collectstatic` step. The key value itself isn't used during that step so using a dummy should work fine.

## Notes and todos

Should we deprecate frontend.sh entirely? Does it still serve any purpose now that we've moved to esbuild? Do we ever use the "development" build? (see below: No)

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)
- [x] Future todos are captured in comments and/or tickets
- [x] Project documentation has been updated, potentially one or more of:
  - [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in the `/docs` folder) – for basic, close-to-the-code docs on working with this repo
  - CFGOV/platform wiki on GHE – for internal CFPB developer guidance
  - CFPB/hubcap wiki on GHE – for internal CFPB design and content guidance

### CODE REVIEW

**Comment by chosak** [comment]
@willbarton that file isn't used. We don't actually use [deployable-zipfile](https://github.com/cfpb/consumerfinance.gov/tree/main/docker/deployable-zipfile) at all anymore -- there's a separate copy under [builder](https://github.com/cfpb/consumerfinance.gov/tree/main/docker/builder) which excludes the frontend build, introduced in #7732.

Currently the GitHub Action that builds the deployable artifact [does its own](https://github.com/cfpb/consumerfinance.gov/blob/b63f58fd824eca2a17c099f9fd2606f1b38670b7/.github/workflows/build-artifact.yml#L23-L27) `yarn` and `yarn run build`, and then those assets are copied into the deployable artifact. If I recall this was done because we couldn't use a modern version of Node on Centos 7.

@wpears is there any reason to keep [deployable-zipfile](https://github.com/cfpb/consumerfinance.gov/tree/main/docker/deployable-zipfile) around anymore? Can we delete it?

**Comment by chosak** [comment]
As part of that cleanup work, we should update [these docs](https://cfpb.github.io/consumerfinance.gov/deployment/#generating-a-deployment-artifact) which hilariously still claim that we build using Centos 6.

**Comment by willbarton** [comment]
@chosak Oh, right. I withdraw my comment.

> @wpears is there any reason to keep [deployable-zipfile](https://github.com/cfpb/consumerfinance.gov/tree/main/docker/deployable-zipfile) around anymore? Can we delete it?

I vote we delete it with all due haste.

**Comment by wpears** [comment]
Yeah we can delete deployable-zipfile now.

re: the frontend stuff, I think it's not that passing `production` to `frontend.sh` is wrong, it's that our `devDependencies` are wrong. `devDependencies` when the javascript is a frontend app should only be testing/linting. This was introduced in the less -> sass conversion: https://github.com/cfpb/consumerfinance.gov/pull/8514/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
So I think we should keep the `production` targets and just move those sass dependencies to the `dependencies` object

**Comment by chosak** [comment]
We discussed this in scrum and a more proper fix to item 1 above is to move the Sass-related packages from devDependencies to dependencies. I've made that change and a few related bits of cleanup to our package lists, including removing `less`, which should have been removed in #8514.

Edit: what Wyatt said.

**Comment by chosak** [comment]
> Yeah we can delete deployable-zipfile now.

Deleted in #8596.

**Review by wpears — APPROVED** [review]

**Pull request merged**
