### PR TITLE
Get rid of old browser tests in the cucumber directory

### PR DESCRIPTION
**Pull request by cwdavies**
Browser tests: figure out what we're missing that we're still interested in
Moved new feature files and step_definitions from `cucumber-new` into `cucumber` directory

## Removals

- Deleted old feature files and step_definitions from `cucumber` directory

## Notes and todos

- Create cypress tests from feature files that were in `cucumber-new` directory

## Checklist

- [x] PR has an informative and human-readable title
  - PR titles are used to generate the change log in [releases](../../releases); good ones make that easier to scan.
  - Consider prefixing, e.g., "Mega Menu: fix layout bug", or "Docs: Update Docker installation instructions".
- [x] Changes are limited to a single goal (no scope creep)
- [ ] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)
- [ ] Future todos are captured in comments and/or tickets
- [ ] Project documentation has been updated, potentially one or more of:
  - [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in the `/docs` folder) – for basic, close-to-the-code docs on working with this repo
  - CFGOV/platform wiki on GHE – for internal CFPB developer guidance
  - CFPB/hubcap wiki on GHE – for internal CFPB design and content guidance

#### Browser testing

Visually tested in the following supported browsers:
- [ ] Firefox
- [x] Chrome
- [ ] Safari
- [ ] Edge 18 (the last Edge prior to it switching to Chromium)
- [ ] Internet Explorer 11 and 8 (via emulation in 11's dev tools)
- [ ] Safari on iOS
- [ ] Chrome on Android

### CODE REVIEW

**Comment by anselmbradford** [comment]
There's this gulp task too https://github.com/cfpb/consumerfinance.gov/blob/main/gulp/tasks/test-acceptance.js 
And this reference https://github.com/cfpb/consumerfinance.gov/blob/main/gulpfile.js#L26

I'd rather we rename the "new" tests to the old locations. Can we do that in this PR, or does that put too many files in motion?

**Comment by cwdavies** [comment]
> There's this gulp task too https://github.com/cfpb/consumerfinance.gov/blob/main/gulp/tasks/test-acceptance.js
> And this reference https://github.com/cfpb/consumerfinance.gov/blob/main/gulpfile.js#L26
> 
> I'd rather we rename the "new" tests to the old locations. Can we do that in this PR, or does that put too many files in motion?

Yes I agree with your recommendation.
I will move the tests from "cucumber-new" into "cucumber" directory.
It does put several files in motion, but as this is a reorganization task it will be done in this PR.

**Comment by anselmbradford** [comment]
[This](https://github.com/cfpb/consumerfinance.gov/blob/main/gulp/tasks/test-acceptance.js) should be replaced with [this](https://github.com/cfpb/consumerfinance.gov/blob/main/gulp/tasks/test-acceptance-new.js) and and [this reference](https://github.com/cfpb/consumerfinance.gov/blob/main/gulpfile.js#L26) should be removed. `gulp test:acceptance --headless` should pass.

**Comment by cwdavies** [comment]
Verified cucumber tests pass:
```
$ gulp test:acceptance --headless
[13:37:03] Requiring task ./gulp/tasks/test-acceptance.js
[13:37:03] Using gulpfile ~/Projects/CFPB/consumerfinance.gov/gulpfile.js
[13:37:03] Starting 'test:acceptance'...
[13:37:03] Running Protractor with params: test/browser_tests/conf.js,--params.headless=true
[13:37:04] I/launcher - Running 1 instances of WebDriver
[13:37:04] I/direct - Using ChromeDriver directly...
.......................................................................................................................................................................................................................................................

24 scenarios (24 passed)
103 steps (103 passed)
0m51.153s
[13:37:56] I/launcher - 0 instance(s) of WebDriver still running
[13:37:56] I/launcher - chrome #01 passed
[13:37:56] Protractor tests done!
[13:37:56] Finished 'test:acceptance' after 53 s
```

**Review by anselmbradford — APPROVED** [review]
LGTM 👍

**Pull request merged**
