### PR TITLE
Change all references from cfgov-refresh to consumerfinance.gov

### PR DESCRIPTION
**Pull request by willbarton**
We've renamed this repository from cfgov-refresh to consumerfinance.gov. This change is to remove all references to cfgov-refresh and ensure they're to consumerfinance.gov.

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)

### CODE REVIEW

**Comment by Scotchester** [comment]
Any idea what the change is in cfgov/agreements/fixtures/agreement_data.json? There are no instances of `consumerfinance.gov` in that file that aren't preceded by `files.`. And, is the file even used? Searching the codebase for `agreement_data` turns up nothing.

**Comment by Scotchester** [comment]
> Any idea what the change is in cfgov/agreements/fixtures/agreement_data.json? There are no instances of `consumerfinance.gov` in that file that aren't preceded by `files.`. And, is the file even used? Searching the codebase for `agreement_data` turns up nothing.

Looks like it's probably the addition of an EOF blank line, judging by the rest of the JSON files in this PR where that is the only update.

**Comment by Scotchester** [comment]
Not at all sure if this is related to this PR or not, but I have to run and wanted to note it before I'm out next week: Can't `docker-compose up` anymore.

```
~/Projects/cfgov-refresh rename-cfgov-refresh* § docker-compose up
Removing cfgov-refresh_python_1
Starting cfgov-refresh_docs_1 ... 
cfgov-refresh_postgres_1 is up-to-date
Starting cfgov-refresh_docs_1                  ... done
Recreating bdae9ab63443_cfgov-refresh_python_1 ... error

ERROR: for bdae9ab63443_cfgov-refresh_python_1  Cannot start service python: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"./docker-entrypoint.sh\": stat ./docker-entrypoint.sh: no such file or directory": unknown

ERROR: for python  Cannot start service python: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"./docker-entrypoint.sh\": stat ./docker-entrypoint.sh: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.
```

**Comment by Scotchester** [comment]
I get the same error on the primary branch, so it's probably not the fault of this PR>

**Comment by willbarton** [comment]
Weird. I'll fix the blank line.

I'll also look at Docker... that's worrying.

**Comment by willbarton** [comment]
Alright, I left out some of the Docker files originally — that's why it wasn't finding the entrypoint script, /srv/cfgov-refresh didn't exist! So that's fixed.

I've also restored the agreement_data.json. I'm not sure why it got changed.

**Comment by Scotchester** [comment]
There are a ton of files which got new EOF blank lines, not just
agreement_data.json, which, for the record, doesn't bother me.

>

**Comment by willbarton** [comment]
> There are a ton of files which got new EOF blank lines, not just

@Scotchester I thought I caught all of them at this point (it bothers me that they'll get this commit message even if it's not relevant).

**Comment by willbarton** [comment]
Good catches, @cwdavies! Both of those are in now.

**Pull request merged**
