### PR TITLE
Remove legacy your-story and foia resources

### PR DESCRIPTION
**Pull request by wpears**
Following https://github.com/cfpb/consumerfinance.gov/pull/7388 and https://github.com/cfpb/consumerfinance.gov/pull/7402, this removes the legacy app entirely, which at this point was just static resources for the foia and your-story pages.

 - Quarterly FOIA reports were moved to S3, matching how files have been uploaded since Q4 2020. This is already live: https://www.consumerfinance.gov/foia-requests/foia-electronic-reading-room/cfpb-foia-quarterly-reports/
 - Rebuilt your-story in Wagtail, uploading needed images. Pretty high fidelity just using a landing page and the differences are just where your-story wasn't conforming to the DS. Also, added Wagtail goodies like share links and email signup in the sidebar. This page is already published and is just shadowed by the route deleted from `urls.py` in this PR. If you want to admire it, it is in the content admin view at `<...>/pages/16895/edit/` -> preview
 
Screen Shot 2022-12-13 at 10 35 53 AM

### CODE REVIEW

**Review by anselmbradford — APPROVED** [review]
This looks reasonable to me.

<table>
  <tr>
    <td>old (current) appearance</td>
    <td>new appearance</td>
  </tr>
  <tr>
    <td>tell-your-story-old</td>
    <td>tell-your-story-new</td>
  </tr>
</table>

Last edited 6 weeks ago by @csebianlander

**Comment by chosak** [comment]
@csebianlander any thoughts on the content changes here?

**Comment by csebianlander** [comment]
Am I wrong that the only significant difference (per ans's screenshots) is the sidebar "About Us" content? If so, I'm OK with this.

**Comment by chosak** [comment]
@csebianlander yes, I believe so. But @anselmbradford I notice that [the Wagtail page](http://localhost:8000/admin/pages/16895/edit/) that Wyatt created includes some hardcoded HTML for the header button:

image

and footer button:

image

Unless I'm mistaken we don't have a way to add standalone CTA buttons like this using regular Wagtail components? @jenn-franklin do you have any ideas on how we might build this page in Wagtail without having to hardcode HTML like this?

**Comment by anselmbradford** [comment]
@csebianlander @jenn-franklin I chatted with Andy about options for this and we discovered that we do have a call to action module in Wagtail, but it wasn't available in Landing Pages, which this page is. How about this for a compromise: we add the call to action module to landing pages, and have a CTA for the submit your story in the body of the page, as we do with /complaint/. Then the button in the hero becomes a link. This would eliminate the custom HTML in wagtail. What do you think?

localhost_8000_admin_pages_16895_edit_preview_


These would be the Wagtail edits:

Screen Shot 2023-03-24 at 5 49 28 PM

Screen Shot 2023-03-24 at 5 49 50 PM

**Comment by jenn-franklin** [comment]
Hi! @chosak—ah, yah. Our hero pattern is not meant to hold a CTA, though I can understand why it does in this situation. Unfortunately I don’t think we have any other pattern that can hold info like this with a button. So I think the best route might be to keep the hardcoded html. 

One nit-picky visual comment: I’m wondering if we can change the hero background color to gray 10 (#e7e8e9) to differentiate it from the sidebar. 

Thanks!

**Comment by csebianlander** [comment]
We can start by hardcoding the button but I can reach out to the content owners for this page and ask whether they're OK with replacing it with a link?

**Comment by wpears** [comment]
@jenn-franklin I updated the hero background color in wagtail:

**Comment by wpears** [comment]
@jenn-franklin I updated the hero background color in wagtail:
Screen Shot 2023-04-19 at 8 50 06 AM

**Pull request merged**
