### PR TITLE
Use prettier as a stylelint plugin and remove custom rules where possible

### PR DESCRIPTION
**Pull request by wpears**
We enforce use of prettier on js yet only stylelint on css. This leads to weird editor inconsistencies and manual config needed to rectify these two tools. Running prettier as a plugin to stylelint during the lint pass makes sure that edit-time prettier fixes are upheld during the lint pass.

As well, we had a number of overrides in the stylelint config that, imo, kinda stamps on one of the reasons to use these tools in the first place: simple, cross-project consistent style with low/no setup. I removed those and relinted the code against the simpler config (these changes are the bulk of this PR).

### CODE REVIEW

**Comment by anselmbradford** [comment]
Have you looked at an approach like https://www.npmjs.com/package/stylelint-config-prettier? I believe this would treat prettier and stylelint as separate tools, but would disable the conflicting rules in stylelint. This is an analog to the ESlint config override https://github.com/cfpb/consumerfinance.gov/blob/main/package.json#L51

**Comment by wpears** [comment]
I think it should be largely the same? Right now in `lint.sh` we don't run prettier against less/css. So running prettier there and then disabling conflicting rules in prettier SHOULD result in the same process as just running a stylelint pass that is configuring to match prettier.

**Comment by anselmbradford** [comment]
Maybe the same/similar, but here check it out :) --> https://github.com/cfpb/consumerfinance.gov/pull/7438

I think that's a bit more idiomatic in regard to Prettier's guidance --> https://prettier.io/docs/en/integrating-with-linters.html, and also makes the linter flow for the CSS and JS the same.

**Comment by wpears** [comment]
Superseded by https://github.com/cfpb/consumerfinance.gov/pull/7438

**Pull request closed without merging**
