### PR TITLE
Removes search.gov snippet

### PR DESCRIPTION
**Pull request by wpears**
This file is not actually being used for anything interesting, yet loads on every page. This stops that.
Also, removing this made me uncover some unused v1 templates and base_elements.py which I removed here as well.

### CODE REVIEW

**Comment by anselmbradford** [comment]
This LGTM :+1:, but I defer to bewds

**Comment by anselmbradford** [comment]
Oh noticed one thing. Does this mean we should remove [these](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/jinja2/v1/_layouts/base.html#L153-L154) also?

If you search for `search.usa.gov` in the codebase there are a few references in retirement and TDP.

**Comment by wpears** [comment]
Fixed!

**Comment by chosak** [comment]
Users of search.gov are instructed to include this JS snippet as part of [the Search.gov activation documentation](https://search.gov/admin-center/activate/code.html), which is currently linked from [the cf.gov documentation](https://cfpb.github.io/consumerfinance.gov/site-search/#site-search).

If we're going to diverge from the recommended integration, we should at minimum document that deviation. The Search.gov team is also very responsive to support inquiries; could we reach out to them to clarify our understanding of this snippet and confirm there aren't any other uses we might be missing?

**Comment by wpears** [comment]
From those docs, we have the following:
> This tag enables typeahead search in the search box on your web pages and powers the data on trending URLs

- `https://search.usa.gov/javascripts/remote.loader.js` 301s to `https://search.usa.gov/assets/sayt_loader.js` (already a smell on those docs, serving a 301 on every page is not great!).
-  Reading the code of `https://search.usa.gov/assets/sayt_loader.js`, typeahead is only activated if there is an element with the class `usagov-search-autocomplete` in the page (which, for us, there never is).
- In the search_gov.html snippet, we just set the usasearch.config `siteHandle` to `cfpb` (+/- `beta` and/or `es`, depending on whether we're on a spanish page or beta).
- The trending URL code is only activated if `enableDiscoveryTag` is set on the config which, as noted above, it never is.

Thus, this code doesn't do anything. Could it? Probably. We could enable discovery and/or autocomplete, but that would also require a change from the status quo and would result in more code being loaded which the current value of is dubious and/or should be done intentionally.

This PR, instead, just removes code that is loaded everywhere but doesn't do anything.

**Comment by wpears** [comment]
I can also say that, in testing the on-site autocomplete that that snippet enables, I found it incredibly ineffectual. With only one query actually giving typeahead results (`re` gave `regulation e`) while many other queries that refer to many common terms on our site (rule, compliance, data, hmda, rent, etc.) returning nothing. I don't doubt there being potential value in such a feature, but we'd need to (1) actually prove this out with user research and (2) make typeahead results far better for them to be worth the JS & css.

**Comment by anselmbradford** [comment]
Looks like the last paragraph on https://github.com/cfpb/consumerfinance.gov/blob/f52ca7c1baee77776fa531aa31dc579fe4ec404b/docs/site-search.md needs an edit

**Review by anselmbradford — APPROVED** [review]

**Pull request merged**
