### PR TITLE
Compress all the new homepage images

### PR DESCRIPTION
**Pull request by contolini**
The hero image went from ~ 450KB to 112KB and all the other images have about 50% reduced filesize. I used a lossy minification tool but played with the settings until there was no discernible visual difference.

## Changes

- Optimized all the homepage images

## How to test this PR

1. `./frontend.sh`
2. http://localhost:8000/ should look identical

### CODE REVIEW

**Comment by chosak** [comment]
Awesome! Could you also do this for the new images I added in #6942?

**Review by chosak — APPROVED** [review]
This LGTM - do we have any internal design/image guidelines around creating images for the web, where it might be helpful to document any recommendations?

**Comment by niqjohnson** [comment]
> This LGTM - do we have any internal design/image guidelines around creating images for the web, where it might be helpful to document any recommendations?

@chosak, we have GHE/CFPB/hubcap/wiki/Wagtail-image-sizing-guidelines-&-tips, which does have a section on homepage images that could be updated. (All the Fireworks love on that page makes me miss @Scotchester all over again 😆 )

**Comment by contolini** [comment]
Thanks all, I updated the wiki with some new tips.

**Comment by Scotchester** [comment]
@niqjohnson I'm glad someone still remembers that page 😄

**Pull request merged**
