### PR TITLE
Make pagination Previous/Next and remove customization option

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- Make pagination Previous/Next and remove customization option

## How to test this PR

1. These pages should have a pagination that says Previous/Next

https://www.consumerfinance.gov/data-research/research-hub/
https://www.consumerfinance.gov/about-us/blog/
https://www.consumerfinance.gov/about-us/events/archive-past-events/
https://www.consumerfinance.gov/about-us/newsroom/
https://www.consumerfinance.gov/activity-log/
https://www.consumerfinance.gov/administrative-adjudication-proceedings/administrative-adjudication-docket/
https://www.consumerfinance.gov/compliance/amicus/briefs/
https://www.consumerfinance.gov/compliance/supervisory-guidance/
https://www.consumerfinance.gov/consumer-tools/auto-loans/answers/ (and all similar Answer results pages across money topic pages)
https://www.consumerfinance.gov/consumer-tools/educator-tools/youth-financial-education/teach/activities/
https://www.consumerfinance.gov/data-research/cfpb-researchers/
https://www.consumerfinance.gov/data-research/prepaid-accounts/search-agreements/
https://www.consumerfinance.gov/data-research/research-hub/
https://www.consumerfinance.gov/data-research/research-reports/
https://www.consumerfinance.gov/enforcement/actions/
https://www.consumerfinance.gov/enforcement/petitions/
https://www.consumerfinance.gov/es/herramientas-del-consumidor/cobro-de-deudas/respuestas/ (and all similar Respuestas results pages across money topic pages)
https://www.consumerfinance.gov/foia-requests/foia-electronic-reading-room/
https://www.consumerfinance.gov/rules-policy/final-rules/
https://www.consumerfinance.gov/rules-policy/notice-opportunities-comment/archive-closed/
https://www.consumerfinance.gov/rules-policy/rules-under-development/

### CODE REVIEW

**Review by willbarton — APPROVED** [review]

**Comment by willbarton** [comment]
> @willbarton what's our policy on this? I think we should probably define these in our own translation files, and not rely on Django/Wagtail's, but I'm not sure if we do that consistently.

@chosak If ours are empty, it'll fall back on what Django/Wagtail define, so I don't think there's an effective difference between blank definitions and no definition.

**Comment by chosak** [comment]
@willbarton sorry, I should have been more specific. I was thinking we should explicitly put these in our .po files, even if Django/Wagtail provides them. This (a) avoids them getting re-added in future runs of `makemessages` (b) serves as a guard in the unlikely event these ever get removed or changed in those packages and (c) allow us to have them explicitly in our codebase so that e.g. a code search finds them.

**Comment by willbarton** [comment]
@chosak alrighty, that makes sense.

So we standardize on explicitly including strings we mark for translation, even if they're not translated?

**Comment by chosak** [comment]
@willbarton I think so? In this case we can likely copy the translations from Django/Wagtail. Basically if `makemessages` finds it, it should be in the PO file, even if we don't (yet) have a translation for it. @anselmbradford what do you think?

**Comment by willbarton** [comment]
@chosak I think that's fine.

> Basically if makemessages finds it, it should be in the PO file, even if we don't (yet) have a translation for it.

Do you think this should apply to all our languages? So if we have no translations, should we generate and commit .po files with empty strings? Right now we're discarding those if they're created (I think we had talked about doing this back when we added the additional languages?), do we want to keep them for all our apps?

**Comment by chosak** [comment]
@willbarton maybe I'm creating a lot of work for little benefit. I hadn't realized that was a deliberate choice in the past. But, yes, I think that would be good for those apps where it applies, so for example yes for v1 but not for, say, retirement, where we don't have any content in non-English/Spanish languages.

**Comment by anselmbradford** [comment]
So, are these the steps I need to do for this PR?

1. Run `./cfgov/manage.py makemessages -l es --ignore=tests`
2. Copy the Previous/Next entries from `cfgov/v1/locale/es/LC_MESSAGE/django.po`
3. Revert all changes generated from `makemessages`
4. Paste in entries from step 2.
5. Add `Anterior`/`Siguiente` for `Previous`/`Next`

Is this right?

**Comment by anselmbradford** [comment]
I added Previous/Next translations text for arabic, spanish, korean, russian, and chinese in

https://github.com/cfpb/consumerfinance.gov/pull/7835/commits/5617ac8ef6dcaabace28769eb9748827782798f7

These are from https://github.com/wagtail/wagtail/blob/6d4265cbfafdf6c0a556bb406aa0e9396fd2d1a4/wagtail/contrib/modeladmin/locale/es/LC_MESSAGES/django.po#L190-L194, etc.

**Pull request merged**
