### PR TITLE
Remove the HMDA Explorer application

### PR DESCRIPTION
**Pull request by Scotchester**
The HMDA Explorer app will be decommissioned on Friday, September 25th. This PR removes it from the repo.

## Removals

- The `hmda` Django app and all related settings, configuration, and documentation

## How to test this PR

1. Wait for the Docker stack to be deployed :)

## Notes and todos

- This should not be merged and deployed until the morning of 9/25.
- If we need to be precious about the timing on 9/25, this could be held in favor simply instituting a redirect from `/data-research/hmda/explore` to wherever we think is best to redirect people.

## Checklist

- [x] PR has an informative and human-readable title
  - PR titles are used to generate the change log in [releases](../../releases); good ones make that easier to scan.
  - Consider prefixing, e.g., "Mega Menu: fix layout bug", or "Docs: Update Docker installation instructions".
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)
- [x] Future todos are captured in comments and/or tickets
- [x] Project documentation has been updated, potentially one or more of:
  - [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in the `/docs` folder) – for basic, close-to-the-code docs on working with this repo
  - CFGOV/platform wiki on GHE – for internal CFPB developer guidance
  - CFPB/hubcap wiki on GHE – for internal CFPB design and content guidance

### CODE REVIEW

**Comment by anselmbradford** [comment]
So long orange explorer!!

**Review by niqjohnson — APPROVED** [review]
This is working for me both locally and in the Docker preview environments: the HMDA Explorer 404s as expected, and the historic data downloads continue to work as in production. I didn't review the code itself, though, but the functionality is working great.

**Comment by Scotchester** [comment]
I've added the Apache rules for redirecting requests to api.consumerfinance.gov that will soon be routed to our prod cf.gov servers. @willbarton would you have time to review?

**Review by willbarton — APPROVED** [review]
At a read-through, the Apache changes look right to me. Hopefully the ALB doesn't do any `Host` mangling.

**Comment by Scotchester** [comment]
For the record, this is how I tested that first regex (before manually testing the URLs in action with the config change):

pythex test showing the regex working for the necessary URLs

**Comment by willbarton** [comment]
Confirmed the redirects against the docker cluster:

```shell
% curl -H 'Host: api.consumerfinance.gov' http://[internal ip/port]/
% curl -H 'Host: api.consumerfinance.gov' http://[internal ip/port]/data/hmda/
% curl -H 'Host: api.consumerfinance.gov' http://[internal ip/port]/data/hmda/concept/agency_code
```
All result in:

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://ffiec.cfpb.gov/data-publication">here</a>.</p>
</body></html>
```

```shell
curl -H 'Host: api.consumerfinance.gov' http://[internal ip/port]/data/hmda/slice/hmda_lar.csv
curl -H 'Host: api.consumerfinance.gov' http://[internal ip/port]/data/hmda/slice/hmda_lar.csv
curl -H 'Host: api.consumerfinance.gov' http://[internal ip/port]/data/hmda/slice/hmda_lar.html
curl -H 'Host: api.consumerfinance.gov' http://[internal ip/port]/data/hmda/slice/hmda_lar.json
curl -H 'Host: api.consumerfinance.gov' http://[internal ip/port]/data/hmda/slice/hmda_lar.jsonp
curl -H 'Host: api.consumerfinance.gov' http://[internal ip/port]/data/hmda/slice/hmda_lar.xml
```

All result in:

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>410 Gone</title>
</head><body>
<h1>Gone</h1>
<p>The requested resource is no longer available on this server and there is no forwarding address.
Please remove all references to this resource.</p>
</body></html>
```

**Comment by Scotchester** [comment]
Converted back to draft because this shouldn't be merged until Friday.

**Pull request merged**
