### PR TITLE
TCCP: Add tooltip with purchase APR context

### PR DESCRIPTION
**Pull request by chosak**
To test, run a local server and visit http://localhost:8000/consumer-tools/credit-cards/explore-cards/cards/. Mouseover the question mark icon.

This implementation works without JavaScript but needs work for mobile. Placement also needs to be moved above the icon per latest design.

## Screenshots

tooltip

## Checklist

- [ ] PR has an informative and human-readable title
  - PR titles are used to generate the change log in [releases](../../releases); good ones make that easier to scan.
  - Consider prefixing, e.g., "Mega Menu: fix layout bug", or "Docs: Update Docker installation instructions".
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)
- [ ] Future todos are captured in comments and/or tickets
- [ ] Project documentation has been updated, potentially one or more of:
  - [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in the `/docs` folder) – for basic, close-to-the-code docs on working with this repo
  - CFGOV/platform wiki on GHE – for internal CFPB developer guidance
  - CFPB/hubcap wiki on GHE – for internal CFPB design and content guidance

#### Browser testing

Check the current browser support cutoff list](https://cfpb.github.io/consumerfinance.gov/browser-support#current-browser-support-metrics) for browsers that are advisable
to prioritize for testing.

#### Accessibility

- [ ] Keyboard friendly (navigable with tab, space, enter, arrow keys, etc.)
- [ ] Screen reader friendly
- [ ] Does not introduce new errors or warnings in [WAVE](https://wave.webaim.org/extension/)

#### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Does not introduce new lint warnings
- [ ] Flexible from small to large screens

### CODE REVIEW

**Comment by caheberer** [comment]
I realize that my original mock-up was using the black with reversed type, but I was thinking we'd follow the style Grad path developed so that we were consistent. Which is gray-5 background with gray-40 border.

**Comment by chosak** [comment]
@caheberer colors updated in latest commit:

image

**Comment by caheberer** [comment]
Thanks for the colors update!

Other design tweaks for @contolini 
- [ ] Add 15px spacing between header and body
- [ ] Add carat

Do we want to expand the width of this so that it takes up less vertical space? I was using two columns (full width on mobile). It doesn't save that much room, so if there's a reason it's this size that's okay too.

**Comment by contolini** [comment]
@caheberer here's the latest updates that I added to this PR. LMK if you want me to reduce the outer padding.

| dates | eligibility |
|--------|-------|
| Screenshot 2024-06-25 at 4 28 08 PM | Screenshot 2024-06-25 at 4 28 14 PM |

**Review by contolini — APPROVED** [review]
Merging in preparation for user testing. Further improvements TBD.

**Comment by caheberer** [comment]
Looks good to me! One tiny thing that doesn't need to happen before testing—could we add a line break before the date span on mobile?

**Comment by contolini** [comment]
@caheberer Yeah most def

**Pull request merged**
