### PR TITLE
Refactor analytics to use canonical @cfpb/cfpb-analytics module

### PR DESCRIPTION
**Pull request by anselmbradford**
Fixes https://github.com/cfpb/consumerfinance.gov/issues/2361

## Changes

- ~~Change the analytics to lazy initialize when the `sendEvent` method is called.~~
- Updates codebase to use @cfpb/cfpb-analytics module.

## How to test this PR

1. ~~Put a `console.log(…)` statement in the init method of the Analytics.js module and `xdescribe` the Analytics-spec tests to skip them and run `yarn jest test/unit_tests/js/modules/Analytics-spec.js` and the console.log should not run. It will run on `main`, showing that the module calls `init()` when it it imported.~~
1. Add `debug-gtm=true` to a URL that fires analytics events and check the console.log. For example, http://localhost:8000/about-us/blog/?debug-gtm=true

### CODE REVIEW

**Review by wpears — DISMISSED** [review]
I think instead of making this change here we should look to refactor our use of analytics more broadly. `apps/analytics-gtm/js/util/analytics-util.js` is largely duplicative of `js/modules/Analytics.js`

`apps/paying-for-college/js/disclosures/utils/Analytics.js` largely copies `js/modules/Analytics.js` instead of importing it.

`fwb-results.js` and `fwb-questions.js` duplicate analytics logic checks.

`getDataLayerOptions` is kinda a leaky abstraction, imo, this should only be called from **inside** `sendEvent` so that calling code only needs to bother with one function. Indeed, regs3k [implements this abstraction locally](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/apps/regulations3k/js/analytics.js#L14-L19). That's how all code should interact with the analytics module, imo.

**Comment by anselmbradford** [comment]
Coverage failure is N/A. It's just because I touched the files.

**Review by contolini — APPROVED** [review]
📦

**Comment by anselmbradford** [comment]
Note that the FilterableListControl sends an action to the data layer, but doesn't send an `event`, so in the debug log when clicking submit on https://www.consumerfinance.gov/about-us/blog/?debug-gtm=true, for example, the event is shown as `undefined`.

**Pull request merged**
