### PR TITLE
Redirects to correct ireg 404s

### PR DESCRIPTION
**Pull request by csebianlander**
We have a series of 404 errors triggered in our Regulations section (https://www.consumerfinance.gov/rules-policy/regulations/) caused by how relative URL paths are being created on certain pages. This is a known tech issue that should be solved in code. However, in the meantime, this PR manually sets up redirects for these 404s (based on use of our internal content crawler's 404 report) so that website functionality is not hamstrung further by this work's placement in the backlog.

When the technological issue is resolved, these redirects should be able to be removed safely.

---

## Additions

- 75 new redirects all focused on a systemic issue in the generation of links in the regulations section

## How to test this PR

1. localhost
2. Navigate to /rules-policy/regulations/1003/2018-01-01/a/
3. Find the link to /rules-policy/regulations/1003/1002/9/
4. Confirm that the link properly resolves to /rules-policy/regulations/1002/9/
5. Check that all other redirects resolve to non-404s

## Notes and todos

- As mentioned, these should be removed if/when the systemic issue that causes them is resolved; likewise, more may need to be added if other links of this nature are generated in the future, until the larger issue is resolved.

## Checklist

- [ ] PR has an informative and human-readable title
  - PR titles are used to generate the change log in [releases](../../releases); good ones make that easier to scan.
  - Consider prefixing, e.g., "Mega Menu: fix layout bug", or "Docs: Update Docker installation instructions".
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)
- [ ] Future todos are captured in comments and/or tickets
- [ ] Project documentation has been updated, potentially one or more of:
  - [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in the `/docs` folder) – for basic, close-to-the-code docs on working with this repo
  - CFGOV/platform wiki on GHE – for internal CFPB developer guidance
  - CFPB/hubcap wiki on GHE – for internal CFPB design and content guidance

### CODE REVIEW

**Comment by chosak** [comment]
@csebianlander this seems fine to me - I know that Will took a look at this briefly last week so just requesting his review in case there's another low-lift fix to pursue.

**Comment by willbarton** [comment]
I'll admit, I don't love this. 

I think my preference for a low-lift fix would be to programmatically edit the links in the data — or even do so by hand. That's a one-time effort that won't require additional follow-up to clean up later, and it's possible that any code to do that automatic editing could be incorporated into the application to avoid this problem (based on like, vague pre-coffee thoughts — this may or may not be true, and feels less true as I write it down).

It's fine as a mitigation if we need a quick fix; are these 404s a major issue we need to resolve ASAP? If so, sure. I don't see a fix for the actual bug being high on the priority list at the moment. 

But I'd almost volunteer to go in an hand-edit these links myself to avoid re-introducing a lot of new Apache redirects.

**Comment by niqjohnson** [comment]
See GHE/CFGOV/platform/issues/3982 for more details. From what I remember of that one, there are two sources of broken iRegs links. One set of bad links (which I think is the set these redirects correct) are links that, like @willbarton said, could be edited by hand to be fixed. The other set is more troublesome and stems from how the URL path changes when an effective version goes from future version to current version to previous version and seems much harder to fix.

All of that to say that there's a wall of more details in that GHE issue if anyone wants to dive deeper.

**Comment by csebianlander** [comment]
I don't really know much about how the data is structured, but if it's possible to find/replace the URL paths referenced in this PR within the actual data, that's definitely preferable to this approach even in the short-term. I'd be happy to do that if I had a better sense of how to work with that data.

Re: whether these redirects address manual or programmatic issues -- this set of URLs represents *all* the 404s captured by our crawler tool, which I would have thought would encapsulate both/any use case as long as it involves internal links within and across Regulations pages. Not sure how best to determine/confirm that.

**Comment by niqjohnson** [comment]
@csebianlander, I don't doubt that those are all the iRegs 404s that our crawler caught, but because of the way effective version URLs change when they go from future version to current version to past version (i.e. future and past versions have an extra directory in their paths that contains the effective date and throws off relative `href`s), there could be more bad links in the future. Which makes me wonder if this isn't better solved with a `RedirectMatch` instead of individual directives since all those bad links follow the same pattern. Check my regex here because I'm rusty, but I'm thinking something like:

```
RedirectMatch permanent ^/rules-policy/regulations/\d{4}/(\d{4}/.*) /rules-policy/regulations/$1
```

That should redirect any iRegs URLs that have two four-digit pieces in them (e.g. `1003/1002` or `1005/1005`) to URLs with just the second four-digit piece and everything that follows. At a glance it looks like that's the pattern all the bad URLs follow, so that might get them all (and any future ones with the same pattern) in one swoop. We'll also want to check to confirm that we don't have any legit iRegs URLs that follow the `/\d{4}/\d{4}/` pattern, but off the top of my head, I think section numbers only go to three digits (like https://www.consumerfinance.gov/rules-policy/regulations/1006/108/), so we're probably safe.

Still probably not super ideal to fix this with a redirect instead of somewhere in the iRegs app, but this feels like the quickest way to fix current and future broken iRegs links and get rid of a ton of 404s that are dragging down our SEO reports.

**Comment by csebianlander** [comment]
Ahh thanks @niqjohnson for that regex -- I'd done some tinkering early on in looking at this but hadn't yet fully confirmed that all the cases I found matched the pattern. I love this approach, though, and it feels like a much cleaner and more reasonable (and still very short-term) solve. @willbarton I'm sure this is still not ideal, but -- thoughts about replacing all the individual redirects with this single RedirectMatch?

**Comment by willbarton** [comment]
@csebianlander I think it's fine.

**Review by wpears — APPROVED** [review]

**Pull request merged**
