### PR TITLE
Add optional Help link to internal documentation

### PR DESCRIPTION
**Pull request by chosak**
This commit adds the ability for a Wagtail editor to set a URL for an internal Wagtail documentation website. If set, a link to that internal website will appear in the Wagtail "Help" menu.

~~This also adds a new redirect, named `cfpb_guide`, that redirects from /admin/cfpb-guide/ to whatever the internal URL has been set to.~~ Edit: see below, this is now named `internal-docs` and redirects from /admin/internal-docs/.

This makes use of the Wagtail [Settings](https://docs.wagtail.org/en/stable/reference/contrib/settings.html) feature.

## Screenshots

In the Wagtail Settings menu there's a new ~~"CFPB Guide"~~"Internal documentation" item:

image

This takes you to a view where a user can (optionally) set the URL for the internal docs:

image

If that is set, then a new link to the internal documentation appears in the Wagtail Help menu:

image

## Testing

To try this out, follow the above steps and confirm that clicking on the new help link takes you to whatever domain you entered there.

## Notes and todos

- [x] TODO: Verify that the guide setting is only available to admins; i.e. ordinary Wagtail users can't change that value.
- [x] TODO: Needs tests.
- [x] TODO: Add mention of this somewhere in the public documentation.

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)

### CODE REVIEW

**Review by willbarton — APPROVED** [review]
I like this approach a lot.

**Comment by csebianlander** [comment]
One thought - can we add another field on the Wagtail back-end that allows the content manager to modify the link label, instead of it just being hardcoded as e.g. "CFPB Guide"? I'm not sure what I actually want to call this link but I think divorcing it from the codebase is a good idea regardless.

**Comment by chosak** [comment]
> One thought - can we add another field on the Wagtail back-end that allows the content manager to modify the link label, instead of it just being hardcoded as e.g. "CFPB Guide"? I'm not sure what I actually want to call this link but I think divorcing it from the codebase is a good idea regardless.

This approach includes a hardcoded URL (/admin/cfpb-guide/) and named URL pattern ("cfpb-guide") that we would presumably share or include elsewhere in the codebase (for example, if we want to add links to this from Wagtail help text). So I'm a little reluctant to have the label potentially deviate too much from this.

One option would be to make this more generic, and allow editors to arbitrarily add as many links as they want to the help menu item. This would be like any other Wagtail modeladmin/snippet thing, where each one would have a URL and a title. The admin URL would be less useful in that case, e.g. /admin/help-links/2/, though.

Do you want to think about a better name than "CFPB Guide" and we can update all references to that?

**Comment by chosak** [comment]
@csebianlander what about "Internal docs" or "Internal documentation", something like that? Then the URL could be e.g. /admin/internal-docs/.

**Comment by chosak** [comment]
> TODO: Verify that the guide setting is only available to admins; i.e. ordinary Wagtail users can't change that value.

This is setup by default; there's a new "CFPB Guide" option under Group settings that allows the "Change" permission to be given to various groups. So for example to give that permission to our "Content manager" group we would check this box [here](http://localhost:8000/admin/groups/31/):

image

**Comment by chosak** [comment]
> TODO: Add mention of this somewhere in the public documentation.

Added a mention of this to the [Contributing to the docs](https://cfpb.github.io/consumerfinance.gov/contributing-docs/) page:

image

**Comment by csebianlander** [comment]
> @csebianlander what about "Internal docs" or "Internal documentation", something like that? Then the URL could be e.g. /admin/internal-docs/.

Works for me!

**Review by csebianlander — APPROVED** [review]

**Pull request merged**
