### PR TITLE
Ensure FIG data field table rows have correct number of columns

### PR DESCRIPTION
**Pull request by contolini**
Fixes a bug that causes some data field table rows to not have enough columns.

Currently, some tables look like this (values 1, 2 and 4 have no third cell):

```
| Valid values | Codes                  | Instructions                |
|--------------|------------------------|-----------------------------|
| 1            | Code 1 - Some thing    |
| 2            | Code 2 - Another thing |
| 3            | Code 3 - Cool thing    | Do not enter more than once |
| 4            | Code 4 - Neat thing    |
```

This PR ensures they all have the same number of cells as the header row:

```
| Valid values | Codes                  | Instructions                |
|--------------|------------------------|-----------------------------|
| 1            | Code 1 - Some thing    |                             |
| 2            | Code 2 - Another thing |                             |
| 3            | Code 3 - Cool thing    | Do not enter more than once |
| 4            | Code 4 - Neat thing    |                             |
```

## How to test this PR

1. Pull down this branch.
1. Ensure that every row in the various data field tables has three `<td>`s instead of only two.
1. Ensure functional tests pass with: `yarn cypress run --spec test/cypress/integration/compliance/small-business-lending/filing-instruction-guide.cy.js --env FIG_URL=/data-research/small-business-lending/filing-instructions-guide/filing-instructions-guide-test/ --config baseUrl=https://<secret dev4 subdomain>.demo.cfpb.gov` (this branch has been deployed to dev4)

## Checklist

- [ ] PR has an informative and human-readable title
  - PR titles are used to generate the change log in [releases](../../releases); good ones make that easier to scan.
  - Consider prefixing, e.g., "Mega Menu: fix layout bug", or "Docs: Update Docker installation instructions".
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)
- [ ] Future todos are captured in comments and/or tickets
- [ ] Project documentation has been updated, potentially one or more of:
  - [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in the `/docs` folder) – for basic, close-to-the-code docs on working with this repo
  - CFGOV/platform wiki on GHE – for internal CFPB developer guidance
  - CFPB/hubcap wiki on GHE – for internal CFPB design and content guidance

#### Browser testing

Visually tested in the following supported browsers:
- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Edge 18 (the last Edge prior to it switching to Chromium)
- [ ] Internet Explorer 11 and 8 (via emulation in 11's dev tools)
- [ ] Safari on iOS
- [ ] Chrome on Android

#### Accessibility

- [ ] Keyboard friendly (navigable with tab, space, enter, arrow keys, etc.)
- [ ] Screen reader friendly
- [ ] Does not introduce new errors or warnings in [WAVE](https://wave.webaim.org/extension/)

#### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Does not introduce new lint warnings
- [ ] Flexible from small to large screens

### CODE REVIEW

**Comment by schbetsy** [comment]
When I try this, it looks like whenever a cell just has a zero in it (e.g. in every N/A Flag field), it doesn't show up in the table. Is that happening for you, or just me? It looks like this:

Screen Shot 2022-11-07 at 5 04 13 PM

**Comment by contolini** [comment]
Aha looks like `0` is falsy for jinja2. I'll make it more explicit.

**Comment by contolini** [comment]
Thanks @schbetsy! I fixed things and added a regression test: `yarn cypress run --spec test/cypress/integration/compliance/small-business-lending/filing-instruction-guide.cy.js --env FIG_URL=/data-research/small-business-lending/filing-instructions-guide/filing-instructions-guide-test/ --config baseUrl=https://<secret dev4 subdomain>.demo.cfpb.gov` (this branch has been deployed to dev4)

Note: The cypress test PR check failure is due to an unrelated issue with CCDB.

**Review by schbetsy — APPROVED** [review]
💯

**Pull request merged**
