### PR TITLE
Handle fig sidenav sizing in css and clean up/document js

### PR DESCRIPTION
**Pull request by wpears**
As a follow-on to https://github.com/cfpb/consumerfinance.gov/pull/7087, this addresses the underlying clipping issue in a simpler way. Namely, instead of using `position: fixed` and adding a class with js + setting the width as a percentage of the body (which `position: fixed` forces you to do), this uses `position: sticky` (relatively new but supported in all browsers we serve js), which just requires the parent element to have a `height` set. Doing this also allowed me to remove the `scrunch` logic.

Also included in this PR:
 - reenable eslint on the js file and add docstrings
 - fixed a bug where sub-headers weren't properly being shown/hidden if a level-3 header was present
 - updated the `headerOffset` and keyed it off the `main` tag's `offsetTop` so it will always be correct.
 
 Testing:
 - Pull and `yarn build`
 - Spin up a `Fig content page`
 - Everything should appear correct at all non-mobile sizes
 
Screen Shot 2022-06-08 at 9 11 43 PM

### CODE REVIEW

**Comment by cooldragontattoo** [comment]
I am not getting the same levels of indentation as your screenshot shows. 
Screen Shot 2022-06-09 at 1 07 16 PM

**Comment by wpears** [comment]
>I am not getting the same levels of indentation as your screenshot shows.

? What seems misaligned? Is it just the difference based on the leading `T` vs the `a`? Also, none of the code changed here would affect that alignment.

**Comment by cooldragontattoo** [comment]
let me point you over to this PR: https://github.com/cfpb/consumerfinance.gov/pull/7090.

it has to do with the text wrapping under 1.1. and 1.2, as it is doing in the screenshot above.

**Comment by wpears** [comment]
Ah! And you've `yarn build`ed and hard refreshed your local page?

**Comment by cooldragontattoo** [comment]
i don't get the reference....  in any case, yes. ran `yarn build`.  indentation still not appearing.

**Comment by wpears** [comment]
So the indentation works in three ways:
 - sets `display: inline-block` (this is done for all `.m-nav-link`s
 - sets `padding-left: 2.5em` which applies the indentation for every line
 - sets `text-indent: -1.875em` which *unindents* just the first line
(the later two rules are [set here](https://github.com/cfpb/consumerfinance.gov/pull/7101/files#diff-da8f0ead897df2738f41f8cd993273466939adc349c6a274cec0fc624f23726fR9-R12)

Looking in dev tools, these rules are indeed being applied:
Screen Shot 2022-06-09 at 2 16 30 PM
Screen Shot 2022-06-09 at 2 16 55 PM

**Review by cooldragontattoo — COMMENTED** [review]
**hard** refresh made it work.

**Review by cooldragontattoo — APPROVED** [review]

**Pull request merged**
