### PR TITLE
Fix expandable accordion BEM

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- Fix expandable accordion BEM

## How to test this PR

1. Note that pages like https://www.consumerfinance.gov/compliance/compliance-resources/small-business-lending-resources/small-business-lending-collection-and-reporting-requirements/small-business-lending-rule-faqs/ do not have an accordion expandable group, but with this PR they do http://localhost:8000/compliance/compliance-resources/small-business-lending-resources/small-business-lending-collection-and-reporting-requirements/small-business-lending-rule-faqs/

### CODE REVIEW

**Comment by wpears** [comment]
The behavior seems identical to me? Can you provides steps to repro the fix?

**Comment by anselmbradford** [comment]
> The behavior seems identical to me? Can you provides steps to repro the fix?

Oh probably need a `yarn install` to fetch the upstream DS changes

**Comment by wpears** [comment]
>Oh probably need a yarn install to fetch the upstream DS changes

I did that and did it again just now, still seems the same!

**Comment by anselmbradford** [comment]
Oh @wpears I realized with this, the first set of expandables is not set to be an accordion (that is maybe a mistake), so you need to test the second set "Covered credit transactions"

**Comment by wpears** [comment]
Oh, I'm dumb. The behavior **SHOULD** be the same. This is just a BEM fix, incorporating a BEM fix in the DS

**Review by wpears — APPROVED** [review]

**Pull request merged**
