### PR TITLE
Alpine Docker Image

### PR DESCRIPTION
**Pull request by jslay-excella**
Switch to `python:3.8-alpine` Docker image in preparation for Kubernetes.

### CODE REVIEW

**Comment by willbarton** [comment]
@jslay-excella will this change anything about our (poorly organized, at best) [Docker documentation](https://cfpb.github.io/consumerfinance.gov/running-docker/)?

**Comment by jslay-excella** [comment]
Everything looks good and passes. Apache changes are in place. Infra is ready.

**Review by willbarton — APPROVED** [review]
Alright. We should communicate with devs who use Docker that the base image is changing before we merge.

Is there reason to preserve the individual commit history here, or can this branch be squashed entirely, or the history compressed somewhat?

This is fantastic work, @jslay-excella. I love the reduced complexity. It looks good to me, with the above two things!

**Comment by jslay-excella** [comment]
> Alright. We should communicate with devs who use Docker that the base image is changing before we merge, what that means, and what they should do.
> 
> Is there reason to preserve the individual commit history here, or can this branch be squashed entirely, or the history compressed somewhat?
> 
> This is fantastic work, @jslay-excella. I love the reduced complexity. It looks good to me, with the above two things!

I've cleaned up the squash commit message to include all the pertinent changes.

**Pull request merged**
