### PR TITLE
Update autoprefixer, postcss, webpack, protractor-retry, and snyk

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- Update autoprefixer, postcss, webpack, and snyk

## How to test this PR

1. PR checks should pass.

### CODE REVIEW

**Comment by Scotchester** [comment]
Missing an offline cache package for yargs-parser 20.2.4.

**Comment by anselmbradford** [comment]
> Missing an offline cache package for yargs-parser 20.2.4.

I swear we'll be onto spindle before I understand how the caching works in yarn.

**Comment by anselmbradford** [comment]
@Scotchester Should be good now when checks pass… I hope.

**Review by Scotchester — APPROVED** [review]
`./frontend.sh` passes locally for me now!

**Pull request merged**
