### PR TITLE
Fix retirement_api test that was failing on 2/29

### PR DESCRIPTION
**Pull request by chosak**
This test didn't properly handle Leap Day logic. Fixed this and added some additional comments to clarify what is being tested.

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)

### CODE REVIEW

**Comment by willbarton** [comment]
Seems fine, but I wonder, any thoughts on stopping time in these tests?

**Comment by chosak** [comment]
@willbarton I considered that, optionally we could test a full matrix of (day age is being calculated x birthday), but this is the minimal change to fix the issue.

**Review by willbarton — APPROVED** [review]
shipit

**Comment by chosak** [comment]
@willbarton I ended up implementing using freezegun to fix a coverage error. Date math is hard...

**Pull request merged**
