### PR TITLE
Switch oah handlebars templates to string constants and templates

### PR DESCRIPTION
**Pull request by wpears**
We include handlebars in here for purely historical reasons. This removes our handlebars templates from owning-a-home (the only place they exist) and excises their dependencies.

Testing:
 - Fire up http://localhost:8000/owning-a-home/explore-rates/
 - Mouse over the chart to check the chart templates.
 - Enter a $1111111 for the house price
 - Change the "Loan type" to check the warning messages
 - Select a county to see that county options are populated correctly

### CODE REVIEW

**Comment by anselmbradford** [comment]
You probs saw, but template-loader-spec unit test needs updating too.

**Comment by anselmbradford** [comment]
Do we care about the missing coverage?

**Comment by wpears** [comment]
Not really, kinda a false coverage change.

**Comment by anselmbradford** [comment]
And is the Jenkins failure the usual flakiness? I can't really decipher the log…

**Comment by wpears** [comment]
indeed 😭

**Review by anselmbradford — APPROVED** [review]
LGTM 👍

**Pull request merged**
