### PR TITLE
Use unittest.mock instead of mock package

### PR DESCRIPTION
**Pull request by chosak**
Currently we install the [mock](https://pypi.org/project/mock/) package as part of our test requirements. Starting in Python 3.3, this package is part of the standard library as [`unittest.mock`](https://docs.python.org/3/library/unittest.mock.html).

This commit replaces all uses of `mock` with `unittest.mock` and removes the test dependency on the external package.

## How to test this PR

All tests pass!

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)

### CODE REVIEW

**Review by cwdavies — APPROVED** [review]
This change is necessary when we upgrade from Python 2 to Python 3.
I verified all tests pass using `tox -e lint` and `tox -e unittest-current`
Ran 1710 tests in 379.510s
OK
  unittest-current: commands succeeded
  congratulations :)

**Comment by cwdavies** [comment]
Should we create a PR to start testing Python 3.3 in Docker by adding a new python3 container?

**Comment by chosak** [comment]
@cwdavies our default Python version is already 3.6.

**Comment by cwdavies** [comment]
> @cwdavies our default Python version is already 3.6.

@chosak Yes, that's right we are already on a new version of Python! It's Django that is on 2.2.

**Pull request merged**
