### PR TITLE
Remove lightly used ClearableInput module

### PR DESCRIPTION
**Pull request by wpears**
The only place this module is used is in the mobile view of GlobalSearch, where it manages the inside-the-input close label. However, this code is shipped to every page on every screen size. Here's that UI in action:

Screenshot 2023-12-04 at 3 07 05 PM

I think the UI looks somewhat confusing with the X to clear the input and the X to hide the search altogether, so outside of the page weight and maintainability savings, I think this results in a cleaner UI:
Screenshot 2023-12-04 at 3 07 20 PM

On top of this, we've found in testing that the site search isn't really used that often as a percentage of total traffic, so the subset of users that would even encounter this change are small (mobile users, who use the site search, who've typed in something they want to clear entirely, who would find it preferable to notice and use the UI element rather than holding the delete key for 2s)

### CODE REVIEW

**Comment by wpears** [comment]
@sonnakim Search is specifically called out in the products list as belonging to XP, happy for ans and jenn to take a look though.

**Comment by sonnakim** [comment]
@wpears Going forward, would you mind tagging our team on sitewide changes like this, so we're aware of what's happening? I hear you about the portfolio split but a change like this impacts both of our teams, since we own sitewide patterns, so even though this one is minor, it's best if we are aware and can raise any concerns if necessary. Thanks!

**Comment by anselmbradford** [comment]
I had this same question (see [GHE]/CFGOV/platform/issues/4205)), so from my perspective it's fine to go. For what it's worth, the original discussions around this decided to retain the x at mobile because it was harder to clear text at mobile (see @natalia-fitzgerald comment in [GHE]/CFGOV/platform/issues/2310#issuecomment-140453).

This PR should include a few more spots this could be cleaned up from:

- Code comment reference to `input-contains-label_after__clear` in `global-search.less` ([here](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/css/molecules/global-search.less#L56))
- Code comment references to `input-contains-label_after__clear` in `forms.less` ([here](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/css/enhancements/forms.less#L16) and [here](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/css/enhancements/forms.less#L32))

- **Removal from TDP**. Note, that TDP has a search that uses this (and has the older "Clear" style). This may use the ClearableInput being deleted in this PR. If so, you'd want to remove the clearable search on TDP too ([here](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/teachers_digital_platform/jinja2/teachers_digital_platform/activity_index_page.html#L41-46)). Also, in `search.spec.js` ([here](https://github.com/cfpb/consumerfinance.gov/blob/main/test/unit_tests/apps/teachers-digital-platform/js/search-spec.js#L14)).


You might want to put a hold on this PR and remove the TDP search features first in another PR and then un-hold this one.

**Comment by wpears** [comment]
>Removal from TDP. Note, that TDP has a search that uses this (and has the older "Clear" style)

@anselmbradford [TDP actually has its own ClearableInput](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/apps/teachers-digital-platform/js/ClearableInput.js), so removing this code will not affect TDP in any way. I'm less concerned with TDP having crufty code in it than a molecule served on every page.

re: topdoc comments, I noticed those but didn't remove them cause I hate topdoc :) I think we should probably remove every topdoc comment entirely cause I don't think it's being used by anyone and there's nothing enforcing that the topdoc comments are correct or match the current implementation. That said, I'll update them here and start a discussion about that separately.

**Comment by jenn-franklin** [comment]
Hi! Checking out USWDS, they don't show an "x" on default but they do once you enter text. 

default:
Screenshot 2023-12-05 at 9 14 50 AM

with text entered:
Screenshot 2023-12-05 at 9 15 01 AM

Based on this and also reviewing previous platform and hubcap threads, I'm hesitant to remove the "x" without more research. 

CC: @natalia-fitzgerald if you have any further insight from previously looking at this when you were on the Platform team

**Comment by wpears** [comment]
>Based on this and also reviewing previous platform and hubcap threads, I'm hesitant to remove the "x" without more research.

The point of this work is to de-specialize our website such that:
 - We're shipping less code to users
 - Changing the website implementation (including adopting USWDS) would become easier as there are less moving pieces
 - There's less code total code to maintain for developers

It's worth noting that our own site's behavior differs from USWDS already (we only show the X on mobile) and I don't really think parity with USWDS should be the goal of our patterns unless we adopt USWDS wholesale. I find it odd as well that USWDS doesn't mention the X whatsoever on their Search component page (and if you actually try to click it, it's a little janky, you actually have to hit the X precisely with your cursor). I think we should only ship code that has a clear, useful benefit to our users and I don't think the X passes muster in that regard.

I understand that there is a very specific user story where the X is useful (as noted above):
 - A mobile user
 - who uses the site search
 - who has typed in something they want to clear entirely
 - who notices the X to clear
 - who finds it preferable to move their hand to tap the UI element rather than holding the delete key on the mobile keyboard

Has this user ever existed? Probably. But is supporting that flow worth shipping this code to every page? I don't think so, specifically because when the X isn't present, the user just has to hold the delete key for 1-3s, which isn't really that punishing of a failure case.

I think also, as noted in my first comment, the X to *close* the search could be mistaken for the X to *clear* the search, which I think think is a distinct negative to including the X in the input outside of the performance and maintainability concerns.

**Comment by wpears** [comment]
@jenn-franklin Have I convinced you? 👼 🕺

**Comment by wpears** [comment]
Here's an interesting middle ground: there's actually a default browser behavior when you set the `input` type to `search`, which is to include a small `x` on the right side of the form. This is actually EXACTLY what's happening in uswds.

So.. how about we do that? We'd have the exact same behavior as USWDS and would be able to drop this custom code. Also there's a nice accessibility benefit in that the `esc` key clears the search as well, which might be easier for some folks than  cmd+a then cmd+x.

This would apply at both desktop:
Screenshot 2023-12-07 at 10 12 13 AM

and mobile:
Screenshot 2023-12-07 at 10 12 27 AM

The desktop version doesn't take up much screen real estate, so I don't think it contradicts the purpose of https://github.local/CFGOV/platform/issues/2310

**Comment by jenn-franklin** [comment]
Ohhhhhh interesting... that sounds amazing to me!

**Pull request merged**
