### PR TITLE
Adjust tccp results key alignment to be more legible

### PR DESCRIPTION
**Pull request by wpears**
Before:
Screenshot 2024-04-04 at 10 50 19 AM

After:
Screenshot 2024-04-04 at 10 56 37 AM

### CODE REVIEW

**Comment by caheberer** [comment]
I'm not sure about this change. I've gone back and forth on how this should be aligned and landed on the "before" @niqjohnson what are your thoughts?

**Comment by wpears** [comment]
Yeah this is kinda a unique situation for a key/legend because the symbols are different widths (which I think is an accessibility win for colorblindness). It was my gut feeling that the labels should be aligned since that's what users are comparing against each other and feels more "scannable" to me without introducing too much separation between the symbol and the label. That said, the symbol and the label do work less together as a unit in my proposal, which may be enough of a drawback to reject this PR.

**Comment by niqjohnson** [comment]
Oooooor what if I complicate this more and add a third option?

column-aligned

Honestly I think all three are readable and usable.

**Comment by caheberer** [comment]
Oooh, Nicholas, you're singing my song. I had this version previously and Dan was like "the icons don't align" so I swapped it, but we could pretend that never happened?

**Comment by wpears** [comment]
Neat! Added in 4735eaf

Screenshot 2024-04-04 at 1 38 35 PM

**Comment by wpears** [comment]
kk, we're aligning like the below screenshot at all screen sizes
Screenshot 2024-04-04 at 1 58 43 PM

**Comment by anselmbradford** [comment]
Prolly favor `rem` > `em` on new CSS

**Comment by wpears** [comment]
>Prolly favor rem > em on new CSS
@anselmbradford The subtlety here is that we actually want the unit to adjust relative to the parent element so that the alignment works on mobile as well without adding a separate media query.

**Comment by chosak** [comment]
Closing in favor of #8303 - these changes have been included there. Thank you @wpears!

**Pull request closed without merging**
