### PR TITLE
Remove heading requirement for InfoUnitGroup

### PR DESCRIPTION
**Pull request by willbarton**
This change removes the attempt to require a heading if `InfoUnitGroup` blocks have intro text.

The attempt to require headings apparently did not work previously, and with our changes to that test in #6452, is now causing content issues.

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)

### CODE REVIEW

**Comment by niqjohnson** [comment]
@willbarton: We should also remove the help text in [`/cfgov/v1/atomic_elements/organisms.py#L80-L81`](https://github.com/cfpb/consumerfinance.gov/blob/fix/infounitgroup/cfgov/v1/atomic_elements/organisms.py#L80-L81) (I think).

**Comment by willbarton** [comment]
@niqjohnson indeed! That's done in effd51d.

**Comment by niqjohnson** [comment]
@willbarton, the help text changes needs migrations too, right?

**Review by niqjohnson — APPROVED** [review]
Everything was working as expected for me in the PR preview environment. I tested all the heading and intro text combinations I could think of—heading only, intro only, heading and intro, no heading or intro—and all of them previewed and published fine.

**Pull request merged**
