### PR TITLE
Keep duplicated filterable list params when paginating

### LINKED ISSUE #2199: Page number form in filterable list pagination molecule drops parameters
## Current behavior
- The page number field in the pagination molecule has a `Go` button next to it to go to the page specified in the input. The issue is [here](https://github.com/cfpb/cfgov-refresh/blob/flapjack/cfgov/jinja2/v1/_includes/molecules/pagination.html#L63), where the parameters from the filter are made into hidden input fields. If you select multiple options of the same vein, say "Category", then only the last parameter in the URL will be used.
- Much less worrisome but still a bug, the last page visited number is maintained in the URL if using that "Go" form.
## Expected behavior
- All parameters should be maintained when going to different pages using the "Go" form.
- The page parameter in the URL should be singular and be the current page visited.
## Steps to replicate behavior
1. Select two or more "Categories" on Blog and filter the results.
2. Scroll to the bottom where the pagination molecule is and increment the number and hit "Go"
3. Note that the URL only contains the last category selected, it's not selected in the filter anymore, and there are 2 page parameters in the URL

@anselmbradford was the one that first reported the duplicated `page` parameter.

### PR DESCRIPTION
**Pull request by wpears**
Closes #2199 from over 4 years ago!

The problem here stemmed from the use of `request.GET.items()`, which returns only the last value when multiple params have the same key, by design.

See https://docs.djangoproject.com/en/3.1/ref/request-response/#django.http.QueryDict.items

Changing to `.lists()` and updating the logic a bit to handle the resulting lists stops params from being dropped.
Also, filtering out the 'page' param prevents the other bug here which was repeated page params in the querystring.

### CODE REVIEW

**Review by willbarton — APPROVED** [review]
This is fine... I'm kind of surprised that we're diving into `request.GET` in a template, though. That should really be done in a Django form that hands off the appropriate values. But so should a lot of other places where we're using request params.

**Comment by anselmbradford** [comment]
@wpears 

Do me a favor… 
 - pull this branch and run it
 - go to http://localhost:8000/blog 
 - expand the filter and check "At the CFPB" and "Director's notebook"
 - click "Apply filters'
 - scroll to the bottom of the results and enter "3" in the pagination component.
 - click "Go"

Do you get this error?

Screen Shot 2020-10-02 at 11 56 31 AM

**Comment by wpears** [comment]
@anselmbradford I did encounter this (once) but I don't think it's related to this PR. I'm looking into the source of the error.

**Comment by wpears** [comment]
Almost certainly related to https://github.com/cfpb/consumerfinance.gov/pull/5984

**Comment by wpears** [comment]
Yeah confirmed, will merge this and PR a different fix (the error is local only)

**Pull request merged**
