### PR TITLE
Add stylelint

### PR DESCRIPTION
**Pull request by anselmbradford**
## Additions

- Add stylelint dependencies to lint CSS/Less.
- Add stylelint to `yarn lint` command.

## Changes

- Lints files and fixes errors.

## How to test this PR

1. `yarn lint` should show no CSS issues.

## Notes and todos

- Stylelint does not parse our media query mixin and we'll need to look into that closer (https://github.com/cfpb/design-system/issues/1353))
- Stylelint is not smart enough to handle apostrophes in the comments and things they are open quotes. Reworded to remove the apostrophes for now.

### CODE REVIEW

**Comment by anselmbradford** [comment]
https://github.com/cfpb/consumerfinance.gov/pull/7012 should go in first.

**Comment by anselmbradford** [comment]
While reviewing, you might want to hide the whitespace changes to see the actual content changes:
Screen Shot 2022-04-18 at 5 35 57 PM

**Comment by contolini** [comment]
> Stylelint does not parse our media query mixin and we'll need to look into that closer (https://github.com/cfpb/design-system/issues/1353))

Should we ignore `less/no-duplicate-variables` globally in `stylelint.config.js` until https://github.com/cfpb/design-system/issues/1353 is resolved? Seems like it adds a lot of noise to the code.

**Comment by anselmbradford** [comment]
> Should we ignore less/no-duplicate-variables globally in stylelint.config.js until https://github.com/cfpb/design-system/issues/1353 is resolved? Seems like it adds a lot of noise to the code.

It is noisy, but if we do it globally it won't catch the other legitimate cases. It also kinda acts as a `TODO` comment this way.

**Comment by anselmbradford** [comment]
> > Should we ignore less/no-duplicate-variables globally in stylelint.config.js until https://github.com/cfpb/design-
> > system/issues/1353 is resolved? Seems like it adds a lot of noise to the code.

> It is noisy, but if we do it globally it won't catch the other legitimate cases. It also kinda acts as a TODO comment this way.

On further thought, I could go either way on this. Upgrading to Less 4 won't fix this. I've opened https://github.com/ssivanatarajan/stylelint-less/issues/6.

**Comment by contolini** [comment]
> On further thought, I could go either way on this. Upgrading to Less 4 won't fix this. I've opened https://github.com/ssivanatarajan/stylelint-less/issues/6.

It's hard for me to gauge from the diff how many comments there are but if it's *hundreds* and a fix is a long ways away then I'd vote to globally ignore it.

**Comment by anselmbradford** [comment]
ok I've ignored the rules in https://github.com/cfpb/consumerfinance.gov/pull/7009/commits/0cf705ca18ebdb30e74e86403f7dff0809fcb073 and left a code comment

**Review by contolini — APPROVED** [review]
👨‍🎨

**Pull request merged**
