### PR TITLE
WIP: RAF tool i18n and configurable county threshold

### PR DESCRIPTION
**Pull request by virginiacc**
Adds a language data attribute to the container element in the RAF tool template and updates the RAF JS to include translations that enable a Spanish-language version of the tool. (Note: the JS should be imported from an npm module when PR is ready for final review)

## Additions

- `data-language` attribute on container element in RAF tool template to pass the page's language to the tool
- New RAF tool struct block with optional `county-threshold` field
- `data-county-threshold` attribute on container element in RAF tool template to pass the optional `county-threshold` value to the tool

## Changes

- Update RAF JS

## How to test this PR

1. Check out branch and run gulp copy & migrations
2. Replace existing `Rental Assistance Finder Tool` block on [English RAF tool page](http://localhost:8000/coronavirus/mortgage-and-housing-assistance/renter-protections/find-help-with-rent-and-utilities/) with new `RAF Tool (configurable)` block 
3. Navigate to [English RAF tool page](http://localhost:8000/coronavirus/mortgage-and-housing-assistance/renter-protections/find-help-with-rent-and-utilities/) and verify that English-language tool content displays as expected
4. In admin, create a new browse page and set page language to Spanish. Add `RAF tool (configurable)` and verify that tool content displays in Spanish.
5. Change language of page to anything other than Spanish or English and verify that tool displays in English
6. Verify that by default, tool shows county dropdown when a state with more than 10 results is selected rather than old threshold of 5 (New Jersey should show county dropdown, Arizona should not)
7. Change `county_threshold` value in RAF Tool block and verify that tool uses new threshold value instead of default 10

## Screenshots

Screen Shot 2021-08-12 at 1 40 26 PM

## Notes and todos

- This PR includes copied RAFT JS. We will either update this PR or open a new one immediately afterwards that imports the JS from a recently-published npm module.

## Checklist

- [ ] PR has an informative and human-readable title
  - PR titles are used to generate the change log in [releases](../../releases); good ones make that easier to scan.
  - Consider prefixing, e.g., "Mega Menu: fix layout bug", or "Docs: Update Docker installation instructions".
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)
- [ ] Future todos are captured in comments and/or tickets
- [ ] Project documentation has been updated, potentially one or more of:
  - [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in the `/docs` folder) – for basic, close-to-the-code docs on working with this repo
  - CFGOV/platform wiki on GHE – for internal CFPB developer guidance
  - CFPB/hubcap wiki on GHE – for internal CFPB design and content guidance

#### Browser testing

Visually tested in the following supported browsers:
- [x] Firefox
- [x] Chrome
- [x] Safari
- [x] Edge 18 (the last Edge prior to it switching to Chromium)
- [x] Internet Explorer 11
- [x] iOS
- [x] Android

#### Accessibility

- [ ] Keyboard friendly (navigable with tab, space, enter, arrow keys, etc.)
- [ ] Screen reader friendly
- [ ] Does not introduce new errors or warnings in [WAVE](https://wave.webaim.org/extension/)

#### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Does not introduce new lint warnings
- [ ] Flexible from small to large screens

### CODE REVIEW

**Comment by mistergone** [comment]
A couple notes on my latest commit:

- I moved the `erap` folder inside `unprocessed` into the `apps` folder. I'm not sure if there was a reason it was out there on its own, but I figured this was better for folder organization.
- Inside that `erap` folder, I simply added `@cfpb/rental-assistance-finder` as an npm dependency.
- I changed the `copy:erap` gulp task to simply move the `main.js` file from inside `unprocessed/apps/erap/node_modules/` to the `routes` folder where it was going before.

If there's any problem with this, let me know, but it seems to be working for me!

**Review by mistergone — APPROVED** [review]
From a front-end perspecrtive, this looks to be worki

**Review by higs4281 — APPROVED** [review]
Works great for me. All features check out.

**Comment by virginiacc** [comment]
Thanks @higs4281 & @mistergone!

**Comment by higs4281** [comment]
Love the translation work, too.

**Pull request merged**
