### PR TITLE
Upgrading psycopg2 to work with python 3.9

### PR DESCRIPTION
**Pull request by baruva**
Upgrading psycog2 to a version that works with our current python version (3.6.9) and the version of python we wish to upgrade to (3.9.9)
---

## Changes

- version upgrade from 2.7.3.2 to 2.8.6

## How to test this PR

1.Clone the repo
2.Using pyenv change your shell's python to version 3.9.9
3. run ip install -r requirements/local.txt in the cloned repo and there should be no problems
4.If you ran into an ssl issue while trying to get the psycog2 version run these commands
`brew install openssl`
`export LDFLAGS="-L$HOME/homebrew/Cellar/openssl@3/3.0.1/lib"`
`export CPPFLAGS="-I$HOME/homebrew/Cellar/openssl@3/3.0.1/include"`
5.The code wouldn't build for the PR checks if the upgrade wasn't also compatible with 3.6.9

## Notes and todos

-

## Checklist

- [ ] PR has an informative and human-readable title
  - PR titles are used to generate the change log in [releases](../../releases); good ones make that easier to scan.
  - Consider prefixing, e.g., "Mega Menu: fix layout bug", or "Docs: Update Docker installation instructions".
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)
- [ ] Future todos are captured in comments and/or tickets
- [ ] Project documentation has been updated, potentially one or more of:
  - [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in the `/docs` folder) – for basic, close-to-the-code docs on working with this repo
  - CFGOV/platform wiki on GHE – for internal CFPB developer guidance
  - CFPB/hubcap wiki on GHE – for internal CFPB design and content guidance

#### Browser testing

Visually tested in the following supported browsers:
- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Edge 18 (the last Edge prior to it switching to Chromium)
- [ ] Internet Explorer 11 and 8 (via emulation in 11's dev tools)
- [ ] Safari on iOS
- [ ] Chrome on Android

#### Accessibility

- [ ] Keyboard friendly (navigable with tab, space, enter, arrow keys, etc.)
- [ ] Screen reader friendly
- [ ] Does not introduce new errors or warnings in [WAVE](https://wave.webaim.org/extension/)

#### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Does not introduce new lint warnings
- [ ] Flexible from small to large screens

### CODE REVIEW

**Comment by jslay-excella** [comment]
Should we include these openssl instructions in our documentation?

**Comment by willbarton** [comment]
Helpfully, Django 2.2.25 includes a commit that [makes clear that it requires psycopg < 2.9](https://github.com/django/django/commit/12141e3116a5df647aff451d47fd27de2bec6394).

**Comment by willbarton** [comment]
> Should we include these openssl instructions in our documentation?

Yes... with the caveat that I'm wary of including the specific version path (`3.0.1`) in our docs because it could end up having a long half-life.

I think we could add something like:

```
brew install openssl
export LDFLAGS="-L$(brew --prefix openssl)/lib"
export CPPFLAGS="-I$(brew --prefix openssl)/include"
```

**Review by willbarton — APPROVED** [review]

**Comment by willbarton** [comment]
Can this PR be closed since the change was also made in (now merged) #6809?

**Pull request closed without merging**
