### PR TITLE
Fix classes for counts of result types

### PR DESCRIPTION
**Pull request by wpears**
Closes https://github.local/CFGOV/platform/issues/4589
This got introduced in https://github.com/cfpb/consumerfinance.gov/pull/8274

rout does some kinda nasty string concatenation to build up selectors that would have been missed in find/replace.

This fixes counts for me:
Screenshot 2024-08-21 at 2 11 23 PM

### CODE REVIEW

**Comment by anselmbradford** [comment]
What do you think about adding a small utility imported into https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/apps/rural-or-underserved-tool/js/common.js that converts `result.type` from camelCase to kebab-case? Then the classes could be kebab and consistent with the rest of the CSS.

**Comment by wpears** [comment]
I'd kinda prefer to leave this as is. Feels like a little speedbump to me that something is different and some wonky JS is touching the classes.

**Review by anselmbradford — APPROVED** [review]

**Comment by anselmbradford** [comment]
Are the `notRuralCase` and `notFoundCase` classes even used?

**Comment by wpears** [comment]
>Are the notRuralCase and notFoundCase classes even used?
yeah, at https://github.com/cfpb/consumerfinance.gov/blob/456383dfb5d3037290117ff56e0b45de41bfd674/cfgov/unprocessed/apps/rural-or-underserved-tool/js/count.js#L67

**Pull request merged**
