### PR TITLE
Rename `info-unit-group-2.html` to `info-unit-group.html` | Rename `info-unit-2.html` to `info-unit.html`

### PR DESCRIPTION
**Pull request by anselmbradford**
I couldn't find any references to this file https://github.com/search?q=repo%3Acfpb%2Fconsumerfinance.gov+info-unit-group.html&type=code

This was added in https://github.com/cfpb/consumerfinance.gov/commit/19bc91ae79d30da80b783eefb1b948dfa68ff90b and used in `cfgov/jinja2/v1/_includes/organisms/half-width-link-blob-group.html`, which was removed in https://github.com/cfpb/consumerfinance.gov/commit/906240b68b0c17c4902ae84f7e71df92b6156125 … it seems info-unit-group.html then hung around since them, without use.

## Removals

- Remove old `info-unit-group.html`

## Changes

- Rename `info-unit-group-2.html` to `info-unit-group.html`

### CODE REVIEW

**Comment by anselmbradford** [comment]
Can anyone tell if `info-unit.html` is actually used? 

`InfoUnit`s are defined in `molecules.py` and references the `info-unit.html` template https://github.com/cfpb/consumerfinance.gov/blob/01e024e65ad2fd5f73300edd0732099e2576e05e/cfgov/v1/atomic_elements/molecules.py#L26

`InfoUnitGroup`s used in wagtail have a `info_units` value set here https://github.com/cfpb/consumerfinance.gov/blob/01e024e65ad2fd5f73300edd0732099e2576e05e/cfgov/v1/atomic_elements/organisms.py#L97

`InfoUnitGroup`s use the `info-unit-group-2.html` template (renamed to `info-unit-group.html` in this PR). 

The `info-unit-group-2.html` template imports the `info-unit-2.html` template. It then takes the `info_unit` value from Wagtail and feeds it into `info-unit-2.html` here https://github.com/cfpb/consumerfinance.gov/blob/01e024e65ad2fd5f73300edd0732099e2576e05e/cfgov/v1/jinja2/v1/includes/organisms/info-unit-group-2.html#L67

The arguments are `(unit, value.format, value.link_image_and_heading, value.border_radius_image)`, where `unit` gets fed into `value` in the `info-unit-2.html` template here https://github.com/cfpb/consumerfinance.gov/blob/01e024e65ad2fd5f73300edd0732099e2576e05e/cfgov/v1/jinja2/v1/includes/molecules/info-unit-2.html#L51

`value` is then never referenced directly in the `info-unit-2.html` macro, only the additional arguments (properties of `value`) are used.

So, it appears to me that the InfoUnit uses the `info-unit.html` template, but in actuality it just hands over values to `info-unit-2.html`, which does the actual rendering. Am I missing something here?

**Review by wpears — APPROVED** [review]

**Comment by wpears** [comment]
>Can anyone tell if info-unit.html is actually used?

I think the answer is "no." `InfoUnit`s aren't used anywhere outside of `InfoUnitGroup`s, which you've correctly identified as controlling the rendering of its child `InfoUnit`s via the `info-group-2` template.

You can test this by just deleting the `template` field from `InfoUnit`s `Meta` class and note no changes to a page with a rendered `InfoUnitGroup`, eg http://localhost:8000/owning-a-home/prepare/

So, could you rename `info-unit-2.html` like you've done in this PR? Probably. I'd also recommend removing the template field from the `Meta` class in general so it's clear it isn't rendering itself (alternatively, `InfoUnit` could keep its template and you could change how info units are rendered in info-unit-groups).

**Comment by anselmbradford** [comment]
Removed `info-unit.html` and renamed `info-unit-2.html` to `info-unit.html` in https://github.com/cfpb/consumerfinance.gov/pull/8453/commits/1739450a9894638e140e05abc09a493205a4bd2c

**Review by wpears — APPROVED** [review]

**Comment by Scotchester** [comment]
Just want to drop in and offer my apologies for creating this situation :)

**Pull request merged**
