### PR TITLE
Send searches on Spanish-language pages to the Spanish search endpoint, update retirement to 0.15.2

### PR DESCRIPTION
**Pull request by Scotchester**
Currently, all searches using the global search box go to the English search. With these updates, Spanish pages will now send searches to our Spanish search index.

It also fixes the width of the button on the Spanish global search form to not cut off the label.

---

## Additions

- `language` parameters in template macros where they didn't always exist before
- Conditionals to change the Search.gov `affiliate`/`siteHandle` properties to `cfpb_es` if the `language` context variable is set to `'es'`
- `show_mega_menu` and `language` params on the Django page header template helper (see cfpb/retirement#268)
- New styles to fix Spanish search button width

## Removals

- Duplicative Search.gov script on Django template `base_update.html`

## Checklist

- [x] PR has an informative and human-readable title
  - PR titles are used to generate the change log in [releases](../../releases); good ones make that easier to scan.
  - Consider prefixing, e.g., "Mega Menu: fix layout bug", or "Docs: Update Docker installation instructions".
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)
- [ ] Project documentation has been updated, potentially one or more of:
  - [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in the `/docs` folder) – for basic, close-to-the-code docs on working with this repo
  - CFGOV/platform wiki on GHE – for internal CFPB developer guidance
  - CFPB/hubcap wiki on GHE – for internal CFPB design and content guidance

### CODE REVIEW

**Review by niqjohnson — COMMENTED** [review]
I am definitely not qualified to review the code, but I checked out the functionality in the PR preview environment, and everything looked good to me. I tried searches for all the kinds of Spanish pages I could think of (Ask questions, blogs, retirement, financial well-being survey), and they all directed me to the Spanish search results as expected. English pages (and all other languages) continued to direct me to English results.

The only question I had was on the retirement tool: is the mega menu not showing up there expected on the PR preview environment? It wasn't showing up for me, but I know there are some related changes in the retirement repo that might fix that, right?

**Comment by Scotchester** [comment]
Thanks for the review, @niqjohnson!

> The only question I had was on the retirement tool: is the mega menu not showing up there expected on the PR preview environment? It wasn't showing up for me, but I know there are some related changes in the retirement repo that might fix that, right?

Yeah, it's dependent on the changes in https://github.com/cfpb/retirement/pull/268. I believe @higs4281 is planning to check them both out together.

**Review by higs4281 — APPROVED** [review]
This works wonders for Spanish site search. 

I tested locally, and this returns Spanish pages for requests from Spanish pages.

Example blog page: /about-us/blog/su-vivienda-cubrir-gastos-coronavirus/
Currently, searching for "hipotecas" from this page returns just 4 results, all of which are pages with errant language settings (English instead of Spanish). When using this branch, corrrecting the blog page's language to Spanish results in 5 pages' worth of results.

On www, without this patch, fixing the blog page's language doesn't help results.

Like @niqjohnson, I could test this on the PR deployment, and the retirement page's global search works as above, but I couldn't get a local combination of the retirement branch and this branch to work, possibly because of redirects that occur on deployed instances. We need to retire the retirement repo.

Do you have a way of confirming megamenu behavior in retirement?

**Comment by Scotchester** [comment]
> I couldn't get a local combination of the retirement branch and this branch to work, possibly because of redirects that occur on deployed instances. We need to retire the retirement repo.
> 
> Do you have a way of confirming megamenu behavior in retirement?

I don't totally follow what you mean by the redirects comment.

Yes, with my retirement PR branch `pip install -e`d in my local virutalenv, I confirm that Before You Claim looks like it should (including now showing the correct logo and global eyebrow links):

**Comment by higs4281** [comment]
I got it to work properly with a manual retirement install. 👍

**Pull request merged**
