### PR TITLE
Add "Data spotlight" category to Research

### PR DESCRIPTION
**Pull request by csebianlander**
This commit adds the category "Data spotlight" to the Research & Reports section, per a D+D Intake request.

---

## Additions

- "Data spotlight" category added to Research & Reports section.

## Screenshots

Category selection visible on Report document detail page:
Screen Shot 2022-02-15 at 2 49 22 PM 1

Filterable search results:
Screen Shot 2022-02-15 at 2 48 59 PM 1

Choosing category within Wagtail:
Screen Shot 2022-02-16 at 10 44 21 AM

## Checklist

- [ ] PR has an informative and human-readable title
  - PR titles are used to generate the change log in [releases](../../releases); good ones make that easier to scan.
  - Consider prefixing, e.g., "Mega Menu: fix layout bug", or "Docs: Update Docker installation instructions".
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code follows the standards laid out in the [CFPB development guidelines](https://github.com/cfpb/development)
- [ ] Future todos are captured in comments and/or tickets
- [ ] Project documentation has been updated, potentially one or more of:
  - [This repo’s docs](https://cfpb.github.io/consumerfinance.gov/) (edit the files in the `/docs` folder) – for basic, close-to-the-code docs on working with this repo
  - CFGOV/platform wiki on GHE – for internal CFPB developer guidance
  - CFPB/hubcap wiki on GHE – for internal CFPB design and content guidance

#### Browser testing

Visually tested in the following supported browsers:
- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Edge 18 (the last Edge prior to it switching to Chromium)
- [ ] Internet Explorer 11 and 8 (via emulation in 11's dev tools)
- [ ] Safari on iOS
- [ ] Chrome on Android

#### Accessibility

- [ ] Keyboard friendly (navigable with tab, space, enter, arrow keys, etc.)
- [ ] Screen reader friendly
- [ ] Does not introduce new errors or warnings in [WAVE](https://wave.webaim.org/extension/)

#### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Does not introduce new lint warnings
- [ ] Flexible from small to large screens

### CODE REVIEW

**Review by chosak — APPROVED** [review]
Nice work.

One nice-to-have might be to alphabetize the items under `'Research Report'` (in ref.py), so that they're ordered more usefully. I notice that the dropdown seems to be in a random order even on [the search page](https://www.consumerfinance.gov/data-research/research-reports/).

image

This would require regenerating the Django database migration. Might be out of scope for this PR, though.

**Comment by csebianlander** [comment]
I think alphabetizing is a good idea, too; I'll set it up as a separate PR.

**Comment by csebianlander** [comment]
@chosak I'm not authorized to merge PRs to main -- should I pull in someone else for another review/approval and to merge?

**Comment by chosak** [comment]
@csebianlander I would be happy to merge... but unfortunately the merging of #6868 means you have to delete and recreate your migration. Note that PR includes a migration 277, and so does yours. If you don't mind re-generating yours, I can re-approve and then merge.

**Comment by csebianlander** [comment]
@chosak let me know if that worked properly...

**Comment by chosak** [comment]
@csebianlander unfortunately it did not, as you can see from the failed validate-migrations test:

> CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0278_data_spotlight, 0278_remove_unused_categories in v1).

I think #6868 must have introduced both 277 and 278, so yours needs to be 279. If you rebase your branch against main (`git fetch origin; git rebase origin/main`) and recreate the migration, that should do the trick.

**Comment by csebianlander** [comment]
Rebased and recreated migration.

**Review by chosak — APPROVED** [review]

**Pull request merged**
