### PR TITLE
Fix expandable group code comment | consolidate and cleanup expandable group `if` blocks

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- ~~Update expandable group code comment `has_top_rule_line` to correct `has_rule` value.~~
- Add missing expandable group code comment `expandables`.
- Move `has_top_rule_line` to bottom of comments since it's not used in the expandable-group template directly.
- Consolidate `value.heading` `if` checks into one `if`/`else` block. 
- Remove unused `if value.has_rule` check and block.

### CODE REVIEW

**Review by wpears — CHANGES_REQUESTED** [review]
I think the correct value *is* `has_top_rule_line`, see https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/v1/atomic_elements/organisms.py#L637

I think it's actually [line 36](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/v1/jinja2/v1/includes/organisms/expandable-group.html#L36) that needs to be updated.

**Review by wpears — CHANGES_REQUESTED** [review]
I think the correct value *is* `has_top_rule_line`, see https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/v1/atomic_elements/organisms.py#L637

I think it's actually [line 36](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/v1/jinja2/v1/includes/organisms/expandable-group.html#L36) that needs to be updated.

**Comment by anselmbradford** [comment]
> I think the correct value is has_top_rule_line, see 
> https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/v1/atomic_elements/organisms.py#L637
> 
> I think it's actually [line 36](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/v1/jinja2/v1/includes/organisms/expandable-group.html#L36) that needs to be updated.

Oh wow, hmm maybe we should kill it entirely if it's been broken and unnoticed?

**Comment by anselmbradford** [comment]
omg I just noticed

> Used in 'render_block.html' to modify classes

And in `render_block.html` we have both `has_top_rule_line` AND `has_rule` 😭 😭 😭 

https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/v1/jinja2/v1/includes/templates/render_block.html#L5
https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/v1/jinja2/v1/includes/templates/render_block.html#L11

For what it's worth, using the crawler I can't find the rule line markup as shown in the expandable group template https://cfgov-crawler.dev-internal.aws.cfpb.gov/?q=%3Cdiv+class%3D%22a-rule-break%22%3E%3C%2Fdiv%3E&search_type=html

**Comment by wpears** [comment]
Yeah, I'm okay removing he top_line_rule if we aren't using it anywhere. Will help to simplify the expandable-group a bit in wagtail

**Comment by wpears** [comment]
>we need to keep has_top_rule_line for now, as many things have that checked and it is not immediately apparent if those things are expandable groups or something else that uses the same variable.

I don't think that's actually true. Removing lines [637-644](https://github.com/cfpb/consumerfinance.gov/blob/b0ce24b0904eb7c91c6527adfa1e69f1d9f7410c/cfgov/v1/atomic_elements/organisms.py#L637-L644) will just remove the class attribute for the ExpandableGroup class only. All other classes remain unaffected, eg, the has_top_rule_line for the InfoUnitGroup: https://github.com/cfpb/consumerfinance.gov/blob/b0ce24b0904eb7c91c6527adfa1e69f1d9f7410c/cfgov/v1/atomic_elements/organisms.py#L94

**Comment by anselmbradford** [comment]
> I don't think that's actually true. Removing lines [637-644](https://github.com/cfpb/consumerfinance.gov/blob/b0ce24b0904eb7c91c6527adfa1e69f1d9f7410c/cfgov/v1/atomic_elements/organisms.py#L637-L644) will just remove the class attribute for the ExpandableGroup class only.

That's correct in terms of it removing the checkbox, but we don't immediately know whether it is or isn't checked for some pages that have ExpandableGroups. If it is unchecked everywhere we could remove it. If it is checked somewhere, `has_top_rule_line` gets passed to `render_block.html` and has an affect there.

**Comment by anselmbradford** [comment]
Put another way, we can search the database for `has_top_rule_line`, but that will return a mix of use cases from things like info unit groups, expandable groups, etc. According to @chosak we'd have to write a custom script to parse out which of those are expandable groups. It could be manually checked too. The number of pages is maybe dozens, but not 100s.

**Comment by wpears** [comment]
Oh, yeah. It's not used in the expandable-group template but in another template that wraps it (render_block). Gross! This seems kinda weird to me, that we have these shared attributes that are rendered in a common way but are defined as class attributes of the various organisms. It would seem a little tighter to either chunk out some shared functionality into another block type, eg, `blocks.RuledBlock` or decorate the `blocks.StructBlock` with shared block definitions.

**Review by wpears — APPROVED** [review]

**Pull request merged**
